### ISSUE TITLE
Reactive for Native Android and iOS ?

### ISSUE THREAD

**Issue by mssaravanan** [TheEightBot/Reactive-Examples#3]
I'm new to Xamarin Development , I going to design fully customized UI , so I choose native Android and iOS , Can I Implement Reactive in Native Xamarin app ? Can you please give me an idea or example . 

Thanks !!!

**Comment by michaelstonis** [comment]
You absolutely can. The examples here are for Xamarin.Forms, but the ViewModel code would carry over to Xamarin.Android and Xamarin.iOS. I would recommend checking out https://reactiveui.net/docs/ for more information.
